### PR TITLE
smtp/client: support async/await workflows

### LINKED ISSUE #267: async await syntax doesn't work
Just a heads up that this doesn't send email successfully when using async/await syntax. The code runs through as if it succeeded (doesn't throw an error), but the email is not sent and `result` logs as `undefined`.

```js
  try {
    const result = await client.send(message);
    console.log('Email sent successfully', result);
  } catch (err) {
    console.error(err);
  }
```

The callback style in the docs works, of course.
```js
  client.send(message, (err, message) => {
    if (err) {
      console.error(err);
    } else {
      console.log('Email sent successfully', message);
    }
  });
```

But it might be good to support both.

### PR DESCRIPTION
**Pull request by zackschuster**
- adds test for `const message = await util.promisify(client.send.bind(client))(new Message(msg))`
- adds `Client#sendAsync` api 
    - combines `Client#send` with a simple promise wrapper
- adds `isRFC2822Date` api to the date module
    - partially verifies awaited output of `Client#sendAsync` and promisified `Client#send`
- fixes an issue with one of the tests
- alters greylist response tracker to use `WeakSet` instead of `WeakMap`

resolves #267 

assuming this gets merged, i'll prepare a PR for a `semver-minor` release

### CODE REVIEW

**Comment by zackschuster** [comment]
added a full-fledged `sendAsync` api that combines the enhancement from ed8c92e with a simple promise wrapper

also fixed an issue with one of the tests

**Comment by zackschuster** [comment]
assuming this gets merged, i'll prepare a PR for a `semver-minor` release.

File: smtp/client.ts [hunk 1]
```diff
@@ -63,12 +63,32 @@ export class SMTPClient {
 				}
 				this.queue.push(stack);
 				this._poll();
+				if (this.queue.every((x) => x !== stack)) {
```
Comment (eleith) [inline smtp/client.ts:66]: i'm a bit confused. is everything in the `queue` (before `stack`) a sent message?

Comment (zackschuster) [reply smtp/client.ts:66]: from my reading, the `queue` only contains _unsent_ messages; however it does seem like there's a window after a connection is established where a message can be de`queue`d and an error can still surface (e.g. from greylisting).

now that i write that out, i'm realizing i should add that as a test case. i'm guessing it'll break this assumption, in which case i'll have to either rethink the success check or rework `queue` behavior.

Comment (eleith) [reply smtp/client.ts:66]: what is the interpretation of this part of the logic then?

Comment (zackschuster) [reply smtp/client.ts:66]: currently, it is "if the message is not in the queue, it was successfully sent"

**Comment by eleith** [comment]
@zackschuster just making sure you aren't waiting on anything on me for this?

**Comment by zackschuster** [comment]
@eleith no, i just need to come up with a better way for tracking if an email is sent. i'm thinking of using a [`WeakSet`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet).

File: smtp/client.ts (hunk 1 above)
Comment (zackschuster) [reply smtp/client.ts]: turns out it isn't necessary to track if messages are sent, as the message's callback is always called deeper in the stack. this also means i've been wrong all this time & it's always been possible to `await` the results of a promisified send. neat!

**Comment by zackschuster** [comment]
@eleith i think we can move forward.

File: smtp/connection.ts [hunk 2]
```diff
@@ -120,10 +120,7 @@ export class SMTPConnection extends EventEmitter {
 	protected tls: boolean | SMTPSocketOptions = false;
 	protected port: number;
 
-	private greylistResponseTracker = new WeakMap<
-		(...rest: any[]) => void,
-		boolean
-	>();
+	private greylistResponseTracker = new WeakSet<(...rest: any[]) => void>();
```
Comment (zackschuster) [inline smtp/connection.ts:123]: made this change in anticipation of aligning with a sent message tracker in `SmtpClient`, only to discover the additional tracker wasn't necessary. at any rate, i think a `WeakSet` is more appropriate here anyway, so i left it in.
